name: Build and Update Manifest

on:
  push:
    branches:
      - main

env:
  APP_NAME: test-a-prod
  IMAGE_NAME: ghcr.io/louishaftmann/kubernetes-test-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            COMMIT=${{ github.sha }}
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Checkout Repo B
        uses: actions/checkout@v6
        with:
          repository: LouisHaftmann/kubernetes-test
          token: ${{ secrets.GIT_PAT }}
          path: config-repo

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update Kubernetes Manifest
        run: |
          cd config-repo/overlays/${{ env.APP_NAME }}

          kustomize edit set image ${{ env.APP_NAME }}=${{ env.IMAGE_NAME }}:${{ github.sha }}

          # Commit and Push changes
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add kustomization.yaml
          git commit -m "chore(release): update ${{ env.APP_NAME}} image tag to ${{ github.sha }}"
          git push
